[project]
name = "aviation-gis-tools"
version = "0.1.0"
description = ""
authors = [
    {name = "Paweł Strzelewicz"}
]
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
]

[tool.poetry]
packages = [{include = "aviation_gis_tools", from = "src"}]

[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"

[dependency-groups]
dev = [
    "pytest (>=9.1.1,<10.0.0)",
    "pylint (>=4.1.2,<5.0.0)"
]

